tenancy_ocid     = "ocid1.tenancy.oc1..aaaaaaaa6ma7kq3bsif76uzqidv22cajs3fpesgpqmmsgxihlbcemkklrsqa"
compartment_ocid = "ocid1.compartment.oc1..aaaaaaaascylaglqxkdzsg3woajozahmtow3psj42ync5jnz6xrqwovhtoxq"
user_ocid        = "ocid1.user.oc1..aaaaaaaalpieyqquaaneneuyiifrtfbzwcr3hqd7tqfoobwq7xr4jv5pfz3a"
fingerprint      = "48:1a:98:8c:cd:f6:63:4b:fb:4d:8d:26:44:aa:37:f6"
private_key_path = "~/.oci/oci_api_key.pem"
region           = "ap-seoul-1"
ssh_public_key   = "~/.ssh/id_rsa.pub"
